language: node_js
node_js:
- '7'
services:
- mongodb
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - mongodb-3.0-precise
    - ubuntu-toolchain-r-test
    packages:
    - mongodb-org-server
    - g++-4.8
services:
- mongodb
branches:
  only:
  - /^v[0-9]/
after_success:
- npm run coverage
- npm run mocha:json
- bash <(curl -s https://codecov.io/bash)
- bash <(curl -s https://codecov.octoblu.com/bash)
deploy:
  provider: npm
  email: serveradmin@octoblu.com
  api_key:
    secure: j4Rw2vUsIP3aH8H6iMcXTTLwm2bI19RBXCAa4xbdGg2/3weu+7C3vTQlhklwFCXgxf42Zt7EkxKbEmVcW5jDcha6YbCVn1KzaX8YdbAwuTc4A17U1KOyaA7SRGTc20XDCabKPEPSGlrwYCqqUEl8f4WvXv4XIJ01neIkOZag7Oo1F9Qgi7MYS/c9Aw6Ugqr7CJE2nVUEmrHzkJrMjGfdam6xVjxKJObvW7bgztKX3SI2dyIM0hkFmJNVnmF9gb8FImHcy21Y6qY6DM3BJueztGLdEQhAmQlrxfLyI4y24Q0SmMTpEGIEb5Vcp2KD2p26VIMb/vGDJetGacLNtfHQFAoKTGWLqB3eddnllpcoFp63BevNnNfXX9wrL1M4dJgodCLbmLTJSnsA+9hHPdVWW/UION5Bs9qKdOU862dx01jWpleCIIMUUdLN0y3PohI6WXQhPcgWtHxbybP0iDX1VgXO/OTI+6tW7tN0U5W7dOTIL3leur1d7SqUlZYb5/knETSMdYS0GOelu08tUwYVmTEY4tH6GtHox7BuGBpkKXqKuKd+wGTC5gnxVEMvIBmEzJZzVltpFo5Jusfcn9og8Uw7OULlcXnkvU62JOEjVeiwKQ3Smb+uPcIXkhLRoj6WTvhuVJcB7Y43Gr4HdtIZb+MTYP4v1/Hil7SLANxNwis=
  on:
    tags: true
    branches: true
